apiVersion: v1
kind: Service
metadata:
  name: k8s-app-service
  namespace: demo
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal
spec:
  selector:
    app: k8s-app
  ports:
    - port: 80
      protocol: TCP
  type: LoadBalancer
