replicaCount: 1

image:
  repository: ghcr.io/delirius325/liatrio-app
  pullPolicy: IfNotPresent
  tag: latest
  branchName: ""


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
