name: Destroy AWS Cloud Infrastructure
on: 
  check_run:
    types: requested_action
jobs:
  # Job to destroy the infrastructure using Terraform
  destroy-infrastructure:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: tf init
        run: terraform init

      - name: tf validate
        run: terraform validate

      - name: tf destroy
        if: github.ref_name == 'main'
        run: terraform destroy -auto-approve -no-color